build:
	gcc -o aup-shell-3    \
	  -I./include         \
	  -I./common          \
	  -I./c5              \
	  c6/sh3.c            \
	  c5/setenv.c         \
	  c5/statuspr.c       \
	  c5/builtin.c        \
	  common/macrostr.c    
